# Generated by Django 4.2.7 on 2023-11-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_quest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncard',
            name='abilities',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pokemoncard',
            name='weakness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
